### ISSUE TITLE
Js 21_22

### ISSUE THREAD

**Issue by MishaMaksymenko** [MishaMaksymenko/mishamaksymenko.github.io#17]
Андрей, так и не придумал уместный Unit-тест для генератора тестов. Плюс там еще возникли нюансы с обработкой JQuery и DOM. 

Но все же хотелось бы получить несколько примеров или идей как это можно реализовать.

Спасибо

**Comment by AndriiLitvin** [comment]
Привет. так я не видел коммента. + тестировщик что то подзабил на вас.  только что случайно увидел что ты тут активировался и делал дз) по поводу JQuery там по идеи не видит его вообще, там просто подключить его в проверяемый файл и все.

**Comment by MishaMaksymenko** [comment]
Привет. Спасибо, что добрался до меня.
Столько зачетов за один раз еще никогда не получал :)

Андрей, что в общем скажешь насчет качества домашек в контексте моего развития на этом курсе? Толк будет?

**Comment by AndriiLitvin** [comment]
если есть желание то при любых будет толк) не сдавайся и все получиться)) и ты 1 из 14 человек тех кто вообще что то делает)) Вообще норм, молодец)
