### ISSUE TITLE
Замечания по работе №4

### ISSUE THREAD

**Issue by AndriiLitvin** [MishaMaksymenko/mishamaksymenko.github.io#3]
http://joxi.ru/VrwlE7qFpwjVmX
там нет бордера

**Comment by MishaMaksymenko** [comment]
Андрей, на самом деле есть, если открыть PSD и внимательно посмотреть (или тогда не понятно зачем их оставили в макете).

Если это принципиально могу убрать, так будет еще проще. Большого труда не составит :)

**Comment by AndriiLitvin** [comment]
http://joxi.ru/Dr8ERJ6Fx3Yqm6
1) там они скрытые. убери(обычно на макете много скрытых слоев, ну некоторые нужны, тип всяческих ховеров а некоторые просто дизайнер забыл удалить)
2) добавь бордер выпадающему меню 
3) подтяни весь блок с контентом вверх
4) позиционируй бекграунд

**Comment by MishaMaksymenko** [comment]
Пункты 1 и 2 исправил.
Правда думаю, что для исправления пункта 2 есть более оптимальный вариант. Что скажешь?
Насчет пунктов 3 и 4, не совсем понятно, уточни, пожалуйста, что имеется ввиду.

**Comment by MishaMaksymenko** [comment]
Кое-что исправил commit: fixed 3_4 (probably) 
Возможно, угадал

**Comment by AndriiLitvin** [comment]
1) вот так не делай .main_list ul {
position: absolute;
left: -9999px;-не правильно.
    opacity: 0;- тоже не кайфово.
нужно вот так:
.main_list ul {
position: absolute;
left:0;
top:30px;
display:none;
}
.main_list li:hover ul {
display:block;
}
Тобиж, виравниваешь так как тебе нужно, и потом чтоб скрыть делаешь display:none; а не   opacity: 0; -так когда делаешь то блок остается на странице и может перекрывать элементы и что то моет не работать например какая то ссылка которая находится под этим блоком+ он будет существовать просто прозрачным и когда ты добавишь блок то он будет отталкиваться от него и будет отступ на высоту скрытого блока.
а при ховере делаешь display:block;

Переделай.

**Comment by MishaMaksymenko** [comment]
Андрей, во-первых, давай закончим с путнками 1,2,3,4. По ним все???

Дальше, насчет меню: только что переделал, чтобы удовлетворить твой запрос :)

Хотя с opacity все ок, ничего там не перекрывается так как расположение left: -9999px
Также Олег на вебинаре отвечает на этот вопрос (https://youtu.be/3rX462opnAg) на 21'40''.
Вот же одна из статей из дз (http://goo.gl/L1LFe8)
Плюс ко всему, Олег верстал это меню на лекции и сбрасывал нам код, в которм используется (visibility: hidden; opacity: 0; / visibility: visible;  opacity: 1;) 

Также попрошу тебя вести здесь диалог и иногда делать обратную связь в виде ответов на мои вопросы, мне так будет легче выполнять необходимы требования. Спасибо

**Comment by AndriiLitvin** [comment]
С 1-4 пунктами все норм.
по поводу выпадающего меню. да можно делать так и в каждого решения есть свои плюсы. Но блин я не понимаю зачем писать лишний код если все может решить одно свойство.
И как нам обьясняли каждый ментор оценивает работы по собственному усмотрению.
на счет твоих комментариев не спорю. Просто пишу с чем сталкивался. Переделывал чужой код и столкнулся с тем что блоки вели себя странно из за opacity. 

И я + занимаюсь бекендом и как то лишьний код меня вечно смущает. 

и да "Правда думаю, что для исправления пункта 2 есть более оптимальный вариант. Что скажешь?". да есть. я как то не учел тот вариант что можно опустить подменю ниже)  ну тогда я смотрел визуально, чего не хватало то и сказал. ну тупонул, бывает) Все мы люди)

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ

**Comment by MishaMaksymenko** [comment]
Спасибо за комментарии, так намного комфортнее ) 

Насчет пункта 2, сначала хотел подменю поставить на уровень ниже z-index ом, но, как показалось, дети не могут быть под родителями.  

А если опускать блок на 1 пиксель, то нужно делать прозрачный ul и задавать фон для всех li подменю. Чтобы оно не пропадало в процессе перемещения указателя на него. Я правильно понял?

Или имеется ввиду какой-то иной вариант?

**Comment by AndriiLitvin** [comment]
Можно сделать ul без бекграунта задать паддинг топ 1 рх и лишкам задавать бекграунд и ширину 100%. при этом ul не опускать,потому что если опустить подменю будет через этот пиксель выделываться. но это лажа мне так кажется. 
проще сделать бордер и не париться.

**Comment by MishaMaksymenko** [comment]
Идею понял, спасибо
париться не буду)
