### ISSUE TITLE
ДЗ 5

### ISSUE THREAD

**Issue by MishaMaksymenko** [MishaMaksymenko/mishamaksymenko.github.io#4]
Привет, Андрей!

Начет этой работы у меня есть несколько комментариев и вопросов
Комментарии:
- не совсем было понятно из задания как должны выглядеть и работать две правые кнопки в меню сверху, поэтому оставил как на картинке первую справа с фоном, а второю только с подчеркиванием при наведении;
- не попался под руку файл otf шрифта Helvetica Neue, поэтому установил шрифт  Helvetica Neue Thin (который использовался как пример в лекции)

А теперь вопросы:
1. Так и не смог добиться полноценного контроля над placeholder ами. Например, при задании им цвета, они получают сероватый оттенок этого цвета. Только когда начинаешь вводить текст, цвет меняется на заданный. Также и шрифт пришлось прописывать для них дополнительно. Так здесь быть?
1. Возможно ли в css задавать фон, который нужет для меню или достаточно обойтись фоновой катринкой??
2. По заданию нужно было выровнять блок по вертикали и горизонтали. Сделал с помошью position: absolute, margin: - X. Насколько это подходящий способ для данного случая?
3. Возможно ли сделать линию ( просвет в ченом фоне после заголовка) не создавая дополнительный блок-обертку для последующих элементов (в данном случае .form)??

Спасибо.

**Comment by AndriiLitvin** [comment]
1. Возможно ли в css задавать фон, который нужет для меню или достаточно обойтись фоновой катринкой??
   не понял вопрос. 
   ну вообще б я сделал так:
   .box задал бы фон
   .form задал     border-top: 5px solid;
2. По заданию нужно было выровнять блок по вертикали и горизонтали. Сделал с помошью position: absolute, margin: - X. Насколько это подходящий способ для данного случая?
   я думаю норм. тут главное чтоб коректно работало) ну есть еще calc() http://htmlbook.ru/css/calc http://habrahabr.ru/post/243821/ с ним тоже можно поигратся
3. Возможно ли сделать линию ( просвет в ченом фоне после заголовка) не создавая дополнительный блок-обертку для последующих элементов (в данном случае .form)??
   можно попробовать внести в форму тот заголовок и ему назначить бордер, ну так как я писал выше мне так кажется адекватнее.

**Comment by MishaMaksymenko** [comment]
Андрей,
Вопрос 1 был про меню, которое находиться сверху странички (синее), там довольно специфическая текстура фона, и я хотел узнать можно ли сделать это с помошью css или просто подгружать картинку в таком случае))

Со 2 понятно

А в 3 если сделать как ты говоришь, бордер получается не прозрачным , так ведь не покатит. Или я что-то не понял.

И там еще выпал один вопрос из списка насчет холдеров:
Так и не смог добиться полноценного контроля над placeholder ами. Например, при задании им цвета, они получают сероватый оттенок этого цвета. Только когда начинаешь вводить текст, цвет меняется на заданный. Также и шрифт пришлось прописывать для них дополнительно. Как здесь быть?

**Comment by AndriiLitvin** [comment]
> Вопрос 1 был про меню, которое находиться сверху странички (синее), там довольно специфическая текстура фона, и я хотел узнать можно ли сделать это с помошью css или просто подгружать картинку в таком случае))

ну там можно вытянуть вот этую странную структуру  но без цвета,  а цвет задать отдельно
ну влюбом случаи нужна будет картинка для создания такого эфекта. ну в крайней мере я не нашел такого фильтра

> А в 3 если сделать как ты говоришь, бордер получается не прозрачным , так ведь не покатит. Или я что-то не понял

еще прописываешь через rbg цвет с прозрачностью

> Так и не смог добиться полноценного контроля над placeholder ами. Например, при задании им цвета, они получают сероватый оттенок этого цвета. Только когда начинаешь вводить текст, цвет меняется на заданный. Также и шрифт пришлось прописывать для них дополнительно. Как здесь быть?

на счет сероватости это поведение самих браузеров, с этим ничего не поделать. или просто подбирать цвет.

**Comment by MishaMaksymenko** [comment]
c rgba хорошая идея, но тогда на цвет бордера влияет фон box (( только что попробовал

Со всем остальным разобрался, спасибо)
