### ISSUE TITLE
ДЗ 5 плюс

### ISSUE THREAD

**Issue by MishaMaksymenko** [MishaMaksymenko/mishamaksymenko.github.io#5]
Здесь захотелось немного заморочится и сохранить пропорции прямоугольников, используя только colspan и rowspan.
Все было бы круто, если бы браузер пропрорционально расчитывал размеры ячеек, относительно количества объединенных. 
Поиски решения этого вопроса не дали результатов. Поэтому добавил еще одну строку и столбец базовых ячеек, чтобы пропорции строились относительно них.
А чтобы всего лишего добра не было видно пришлось немного считерить и обернуть таблицу в div, оставив в его пределах только необходимое.

Может есть все таки какой то способ контроля пропорциональности при объединении?

**Comment by AndriiLitvin** [comment]
:+1:  так эту работу еще никто не выполнял)) бордеры заливка) да все ок(в задании написано "Визуально верстка должна быть похожа на картину, но сохранение пропорций прямоугольников не обязательно, нужно использовать colspan и rowspan")
тут все круто убери только бордер внизу и справа http://joxi.ru/DmBD8bNuXPX5AP

**Comment by MishaMaksymenko** [comment]
Спасибо)
Говорю же, что немного поиграться захотелось )

Убрал, 
но, если чесно, непонятно, как тебе их видно, я смотрел в трех браузерах и на маке, они были скрыты

**Comment by AndriiLitvin** [comment]
хз. Я с линукса сижу через хром.

**Comment by MishaMaksymenko** [comment]
надеюсь уже не видно)

**Comment by MishaMaksymenko** [comment]
с этим закончили?

**Comment by AndriiLitvin** [comment]
да тут норм. 5 работа я же написал что ЗАЧЕТ
