### ISSUE TITLE
ДЗ 6

### ISSUE THREAD

**Issue by MishaMaksymenko** [MishaMaksymenko/mishamaksymenko.github.io#6]
Такая верста, конечно, далека от эталонов пиксельной точности. Но пока все что успел на данный момент.
Вышла какая-то каша со шрифтами, многие надписи на страничке получились шире чем в макете, пришлось использовать letter-spacing (хотя не везде удается подогнать). Так же обратил внимание, что в макете размер шрифтов не целые числа, может еще из-за этого.

Хочу еще узнать:
по блоку с товарами (там где шыны):
1. как корректно написать код, чтобы название, картинка и цена были ссылкой?
2. ...я сделал ссылку блоком с прозрачным фоном и наложил ее сверху этих болоков, имеет ли место быть такой вариант?
3. во всем этом блоке стоило ли использовать список, так как это по сути большое меню или достаточно обойтись блоками?
4. в данном случае с товарами, картинки лучше вносить через фон в css или html?

насчет правого сайдбара:
корректно ли использовать список с вложенным списком для его формирования или достаточно сделать 3 маленьких списка?

и в макете была тень по диагонали, есть ли возможность задавать такую в css или не париться и делать обычную?

пока вроде все)
если что-то вспомню допишу.

Извини что назадавал так много вопросов. Ответь, пожалуйста, хотя бы на самые значимые.
Спасибо

**Comment by AndriiLitvin** [comment]
> Вышла какая-то каша со шрифтами, многие надписи на страничке получились шире чем в макете, пришлось использовать letter-spacing (хотя не везде удается подогнать). Так же обратил внимание, что в макете размер шрифтов не целые числа, может еще из-за этого.

там просто возможно размер задан в других еденицах измерения https://learn.javascript.ru/css-units

1)запихни весь код в тег "а", так как ты сделал еще не видел) 
2) каждый вариант имеет право на жизнь но лучше так не делать. нет смысла.
3) в общем это на свое усмотрение делай как тебе удобней
4)html

> насчет правого сайдбара:
> корректно ли использовать список с вложенным списком для его формирования или достаточно сделать 3 маленьких списка?

Думаю да. но можно и без него обойтись. тут тоже много спорных моменттов

> и в макете была тень по диагонали, есть ли возможность задавать такую в css или не париться и делать обычную?

http://css3gen.com/box-shadow/ посмотри там визуально все видно + и код генерится

**Comment by AndriiLitvin** [comment]
ЗАМЕЧАНИЯ:
Переделай то что я писал выше
и 
http://joxi.ru/ZrJyzPXsJWnjAj
1)Что то пошло не так) текст поехал
2)тень сделай по диагонале
3)Там тени нет
4) там тень есть
5)+тень
6)убери эту рамку
7)чекбоксы не соответствуют макету

Пересмотри код, сделай пиксельную точность.

**Comment by MishaMaksymenko** [comment]
переделал
1) +
2) +
3) +
4) +
5) +
6) +
7) +
исправлено

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
