### ISSUE TITLE
Замечания по работе 5 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [MishaMaksymenko/mishamaksymenko.github.io#7]
http://joxi.ru/5mdMgP7ix19K21

1) сделай чтоб фон на весь экран был

**Comment by MishaMaksymenko** [comment]
сделал :)

**Comment by AndriiLitvin** [comment]
http://joxi.ru/MAjlEL1FV7nNme
1)сверстай это с помощью after before
2)сделай чтоб при ресайзе окна менюшка не улетала вправо. вкинь весь контент в контейнер и ему задай ширину и выравнивание по центру

**Comment by MishaMaksymenko** [comment]
фон меню должен тянуться или дотаточно ограничить его пределами контейнера??

**Comment by AndriiLitvin** [comment]
тянуться

**Comment by MishaMaksymenko** [comment]
пофиксил

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
