### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [MishaMaksymenko/mishamaksymenko.github.io#8]
у тебя не совсем правильно медиа квери судя по вчерашниму вебинару то там такие экраны
320-479 480-767 768-959 и 960
## 1. экран 960 http://joxi.ru/p277aN5s03RE62

1)2)6)text-shadow
3)4) нет стрелок влево вправо
5)нет навигации слайдера
7)нет ховера
8)нет навигации
9)две последние букві не таким цветом
10)не тот цвет + text-shadow
тут вообще по всему макету text-shadow. пересмори
## 2.Экран 768 http://joxi.ru/LmGD9PEuR48p72

1)картинки полезли 
2)сделай хоть какие то отступы
3)4)ширина меньше
5)у футера высота больше
- предыдущие правки
## 3. Экран 480 http://joxi.ru/VrwlE7qFKVQbzm

что то вообще не соответствует макету
## 4. Экран 320 http://joxi.ru/RmzkEJqFWXz7d2

1) меню не работает
2)5) не соответствует макету
3) отцентрируй
4)там менюшки нет
- я так понимаю работа еще не готова

**Comment by MishaMaksymenko** [comment]
Я это вчера тоже понял, жаль что в задании не было указано требования к экранам. 
Буду переделывать)

**Comment by MishaMaksymenko** [comment]
Андрей, проверь, пожалуйста)

**Comment by MishaMaksymenko** [comment]
А и еще один момент касающийся работы браузеров. (ОС Windows)

Заметил что Chrome, когда устанавливаешь ширину окна, расчитывает ширину с учетом ширины вертикального скролла, но при этом содержимое выталкивает, только на видимую часть. То есть когда ставлю, например, 1000, реальная ширина = (1000 - ширина скролла), а медиа сработает как на 1000.

Насчет MOzilla, тоже есть нюанс. Он связан с тем что media срабатывает с задержкой в пикселей 5. То есть если media max-with 1000, то реально срабатывает на 995.

Непонятно

**Comment by MishaMaksymenko** [comment]
а и еще!
для 960 лучшего способа как прикрутить стрелки слайдера не придумал, так что макет получился немного кастомизированным

**Comment by AndriiLitvin** [comment]
вообще не плохо.
есть пару замечаний

## нужно сюда добавить 9 задание та как все засчитывается  в один экзамен
- text-shadow по всему макету(пересмотри пожалуйста)
- логотипы компаний, там сделай обычными картинками так как по сути они могут меняться а для этого менять спрайты не фонтан.

**Comment by MishaMaksymenko** [comment]
Спасибо :)

Что же с этим text-shadow?) Буду проверять
Логотипы, переделаю

про 9 помню, сделаю во Вторник

**Comment by AndriiLitvin** [comment]
> Что же с этим text-shadow?) Буду проверять 

ну всмысле он везде есть в основном такой text-shadow: 0px 1px 0px #ffffff;

**Comment by MishaMaksymenko** [comment]
тени добавил, уже больше не знаю куда добавлять
логотипы переделал

**Comment by MishaMaksymenko** [comment]
IE11+, IE10+, IE9+, IE8+ (HTML5 тэги и медиа работают)
Opera 15+ работает
Mozilla 5+ работает
Chrome latest  работает

**Comment by AndriiLitvin** [comment]
## экран 768 http://joxi.ru/eAO1zP7i4xQKYm

1) подровняй 
- семантические теги нужны в этой работе

http://joxi.ru/EA4vLykFDwjkQm - отцентрируй

**Comment by MishaMaksymenko** [comment]
Подровнял, отцентрировал + Html5 теги добавил

**Comment by AndriiLitvin** [comment]
http://joxi.ru/brR6zPluQ7Keer -от центрируй и будет зачет

**Comment by MishaMaksymenko** [comment]
В браузере сделал, а в css внести забыл, извини.
Уже по центру

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
